USE RESORTDB
GO 

INSERT INTO PACKAGE(PACKAGE_NAME,NUM_DAYS,NUM_GUESTS,COST) VALUES('WORKING LIKE A BEE',96,10,2000)
INSERT INTO PACKAGE(PACKAGE_NAME,NUM_DAYS,NUM_GUESTS,COST) VALUES('NEVER ALONE',25,4,1000)
INSERT INTO PACKAGE(PACKAGE_NAME,NUM_DAYS,NUM_GUESTS,COST) VALUES('HIGH TECH',34,2,2000)
INSERT INTO PACKAGE(PACKAGE_NAME,NUM_DAYS,NUM_GUESTS,COST) VALUES('DRINK TILL DIE',82,3,3000)
