USE RESORTDB
GO

INSERT INTO ROOM_RENT(ROOM_TICKET_ID,ROOM_RENT_BID,ROOM_RENT_ID) VALUES(2,3,202)
INSERT INTO ROOM_RENT(ROOM_TICKET_ID,ROOM_RENT_BID,ROOM_RENT_ID) VALUES(3,4,302)
INSERT INTO ROOM_RENT(ROOM_TICKET_ID,ROOM_RENT_BID,ROOM_RENT_ID) VALUES(4,5,402)
INSERT INTO ROOM_RENT(ROOM_TICKET_ID,ROOM_RENT_BID,ROOM_RENT_ID) VALUES(5,6,506)
INSERT INTO ROOM_RENT(ROOM_TICKET_ID,ROOM_RENT_BID,ROOM_RENT_ID) VALUES(6,7,103)
INSERT INTO ROOM_RENT(ROOM_TICKET_ID,ROOM_RENT_BID,ROOM_RENT_ID) VALUES(7,8,204)
INSERT INTO ROOM_RENT(ROOM_TICKET_ID,ROOM_RENT_BID,ROOM_RENT_ID) VALUES(8,9,307)
