USE RESORTDB
GO 

INSERT INTO COMPANY(COMPANY_NAME) VALUES('Microsoft Corporation')
INSERT INTO COMPANY(COMPANY_NAME) VALUES('Amazon.com Inc.')
INSERT INTO COMPANY(COMPANY_NAME) VALUES('Alphabet Inc. Class A')
INSERT INTO COMPANY(COMPANY_NAME) VALUES('Facebook Inc. Class A')
INSERT INTO COMPANY(COMPANY_NAME) VALUES('Alphabet Inc. Class C')
INSERT INTO COMPANY(COMPANY_NAME) VALUES('Tesla Inc')
INSERT INTO COMPANY(COMPANY_NAME) VALUES('NVIDIA Corporation')
INSERT INTO COMPANY(COMPANY_NAME) VALUES('Berkshire Hathaway Inc. Class B')
INSERT INTO COMPANY(COMPANY_NAME) VALUES('JPMorgan Chase & Co.')
INSERT INTO COMPANY(COMPANY_NAME) VALUES('Johnson & Johnson')
