USE RESORTDB
GO 

INSERT INTO BRANCH(PROVINCE,ADDR,PHONENUM,EMAIL) VALUES('Da g','36 Lam Hoanh, Phuoc My ward, Son Tra district',999289962,'CN2@resort.io')
INSERT INTO BRANCH(PROVINCE,ADDR,PHONENUM,EMAIL) VALUES('Buon Me Thuat','3 Phan Chu Trinh, Buon Me Thuat',896218059,'CN3@resort.io')
INSERT INTO BRANCH(PROVINCE,ADDR,PHONENUM,EMAIL) VALUES('Sai Gon','76 Le Lai, Ben Thanh ward, district 1',559328587,'CN4@resort.io')
INSERT INTO BRANCH(PROVINCE,ADDR,PHONENUM,EMAIL) VALUES('Sai Gon','141 Nguyen Hue, Ben Nghe ward, district 1',559339122,'CN5@resort.io')
INSERT INTO BRANCH(PROVINCE,ADDR,PHONENUM,EMAIL) VALUES('Ha Noi','D8 Giang Vo, Ba Dinh district',306099757,'CN6@resort.io')
INSERT INTO BRANCH(PROVINCE,ADDR,PHONENUM,EMAIL) VALUES('Ha Noi','13 Au Trieu, Hoan Kiem district',898084217,'CN7@resort.io')
INSERT INTO BRANCH(PROVINCE,ADDR,PHONENUM,EMAIL) VALUES('Vung Tau','159 Thuy Van, Thang Tam ward',994928438,'CN8@resort.io')
INSERT INTO BRANCH(PROVINCE,ADDR,PHONENUM,EMAIL) VALUES('Phu Yen','77 Duy Tan,  ward 5, Tuy Hoa district',897301396,'CN9@resort.io')
INSERT INTO BRANCH(PROVINCE,ADDR,PHONENUM,EMAIL) VALUES('Binh Dinh','2 Nguyen Trung Tin, Nguyen Van Cu, Quy Nhon city',522909515,'CN10@resort.io')
INSERT INTO BRANCH(PROVINCE,ADDR,PHONENUM,EMAIL) VALUES('Binh Dinh','44 An Duong Vuong, Quy Nhon city',566230397,'CN11@resort.io')
