USE RESORTDB
GO 

INSERT INTO ZONEE(ZONE_BID,ZNAME) VALUES(1,'ZONE B')
INSERT INTO ZONEE(ZONE_BID,ZNAME) VALUES(1,'ZONE C')
INSERT INTO ZONEE(ZONE_BID,ZNAME) VALUES(2,'ZONE B')
INSERT INTO ZONEE(ZONE_BID,ZNAME) VALUES(3,'ZONE D')
INSERT INTO ZONEE(ZONE_BID,ZNAME) VALUES(4,'ZONE E')
INSERT INTO ZONEE(ZONE_BID,ZNAME) VALUES(5,'ZONE A')
INSERT INTO ZONEE(ZONE_BID,ZNAME) VALUES(6,'ZONE C')
INSERT INTO ZONEE(ZONE_BID,ZNAME) VALUES(7,'ZONE B')
INSERT INTO ZONEE(ZONE_BID,ZNAME) VALUES(8,'ZONE D')
INSERT INTO ZONEE(ZONE_BID,ZNAME) VALUES(9,'ZONE A')
