USE RESORTDB
GO 

INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('STANDARD','75',2,'None')
INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('MINIMALISTIC','82',3,'None')
INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('DELUXE','91',5,'None')
INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('STUDIO','102',5,'None')
INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('CONNECTING','200',9,'None')
INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('SUITES','105',5,'None')
INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('JUNIOR SUITES','110',7,'None')
INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('PRESIDENTIAL SUITES','150',8,'None')
INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('PENTHOUSE SUITES','220',10,'None')
INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('HONEYMOON SUITES','140',2,'None')
INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('BRIDAL SUITES','160',2,'None')
INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('APARTMENT','180',8,'None')
INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('VILLAS','210',9,'None')
INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('CABANAS','185',9,'None')
INSERT INTO ROOMTYPE(TYPENAME,[AREA (m2)],NUMGUEST,INFOR) VALUES('BUNGALOWS','240',10,'None')
