USE RESORTDB
GO

INSERT INTO BEDINFO(BED_TID,SIZE,CAPACITY) VALUES(2,1.5,2.0)
INSERT INTO BEDINFO(BED_TID,SIZE,CAPACITY) VALUES(3,1.8,4.0)
INSERT INTO BEDINFO(BED_TID,SIZE,CAPACITY) VALUES(4,2.0,7.0)
INSERT INTO BEDINFO(BED_TID,SIZE,CAPACITY) VALUES(5,1.5,9.0)
INSERT INTO BEDINFO(BED_TID,SIZE,CAPACITY) VALUES(6,1.8,1.0)
INSERT INTO BEDINFO(BED_TID,SIZE,CAPACITY) VALUES(7,2.0,7.0)
INSERT INTO BEDINFO(BED_TID,SIZE,CAPACITY) VALUES(8,2.0,4.0)
INSERT INTO BEDINFO(BED_TID,SIZE,CAPACITY) VALUES(9,2.0,5.0)
INSERT INTO BEDINFO(BED_TID,SIZE,CAPACITY) VALUES(10,2.0,5.0)
INSERT INTO BEDINFO(BED_TID,SIZE,CAPACITY) VALUES(11,1.6,6.0)
