USE RESORTDB
GO

INSERT INTO ROOM(ROOM_BID,ROOMID,ROOM_TID,ROOM_ZNAME) VALUES('2','202',2,'ZONE B')
INSERT INTO ROOM(ROOM_BID,ROOMID,ROOM_TID,ROOM_ZNAME) VALUES('2','201',1,'ZONE B')
INSERT INTO ROOM(ROOM_BID,ROOMID,ROOM_TID,ROOM_ZNAME) VALUES('3','202',3,'ZONE D')
INSERT INTO ROOM(ROOM_BID,ROOMID,ROOM_TID,ROOM_ZNAME) VALUES('4','302',4,'ZONE E')
INSERT INTO ROOM(ROOM_BID,ROOMID,ROOM_TID,ROOM_ZNAME) VALUES('5','402',5,'ZONE A')
INSERT INTO ROOM(ROOM_BID,ROOMID,ROOM_TID,ROOM_ZNAME) VALUES('6','506',6,'ZONE C')
INSERT INTO ROOM(ROOM_BID,ROOMID,ROOM_TID,ROOM_ZNAME) VALUES('7','103',7,'ZONE B')
INSERT INTO ROOM(ROOM_BID,ROOMID,ROOM_TID,ROOM_ZNAME) VALUES('8','204',8,'ZONE D')
INSERT INTO ROOM(ROOM_BID,ROOMID,ROOM_TID,ROOM_ZNAME) VALUES('9','307',9,'ZONE A')
