USE RESORTDB
GO

INSERT INTO SUPPLY_TYPE(SUPPLY_TYPE_NAME) VALUES('LAMP')
INSERT INTO SUPPLY_TYPE(SUPPLY_TYPE_NAME) VALUES('PILLOW')
INSERT INTO SUPPLY_TYPE(SUPPLY_TYPE_NAME) VALUES('BEDDINGS')
INSERT INTO SUPPLY_TYPE(SUPPLY_TYPE_NAME) VALUES('SHEETS')
INSERT INTO SUPPLY_TYPE(SUPPLY_TYPE_NAME) VALUES('TABLE')
INSERT INTO SUPPLY_TYPE(SUPPLY_TYPE_NAME) VALUES('CHAIR')
INSERT INTO SUPPLY_TYPE(SUPPLY_TYPE_NAME) VALUES('MENU')
INSERT INTO SUPPLY_TYPE(SUPPLY_TYPE_NAME) VALUES('GARBAGE BAGS')
INSERT INTO SUPPLY_TYPE(SUPPLY_TYPE_NAME) VALUES('24 INCH TOWEL BAR')
INSERT INTO SUPPLY_TYPE(SUPPLY_TYPE_NAME) VALUES('SHOWER CURTAIN')
