USE RESORTDB
GO

INSERT INTO SUPPLY_IN_ROOM(SIR_SUPPLYID,SIR_TID,NUM_SUPPLY) VALUES(2,6,18)
INSERT INTO SUPPLY_IN_ROOM(SIR_SUPPLYID,SIR_TID,NUM_SUPPLY) VALUES(3,13,20)
INSERT INTO SUPPLY_IN_ROOM(SIR_SUPPLYID,SIR_TID,NUM_SUPPLY) VALUES(2,13,19)
INSERT INTO SUPPLY_IN_ROOM(SIR_SUPPLYID,SIR_TID,NUM_SUPPLY) VALUES(9,8,19)
INSERT INTO SUPPLY_IN_ROOM(SIR_SUPPLYID,SIR_TID,NUM_SUPPLY) VALUES(4,9,1)
INSERT INTO SUPPLY_IN_ROOM(SIR_SUPPLYID,SIR_TID,NUM_SUPPLY) VALUES(4,3,6)
INSERT INTO SUPPLY_IN_ROOM(SIR_SUPPLYID,SIR_TID,NUM_SUPPLY) VALUES(3,12,17)
INSERT INTO SUPPLY_IN_ROOM(SIR_SUPPLYID,SIR_TID,NUM_SUPPLY) VALUES(1,8,3)
INSERT INTO SUPPLY_IN_ROOM(SIR_SUPPLYID,SIR_TID,NUM_SUPPLY) VALUES(5,2,7)
INSERT INTO SUPPLY_IN_ROOM(SIR_SUPPLYID,SIR_TID,NUM_SUPPLY) VALUES(6,6,20)
