from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Branch)
admin.site.register(BranchPic)
admin.site.register(Bedinfo)
admin.site.register(Bill)
admin.site.register(BillService)
admin.site.register(Bookticket)
admin.site.register(BranchHaveRoomtype)
admin.site.register(Company)
admin.site.register(Customer)
admin.site.register(Estate)
admin.site.register(Package)
admin.site.register(ProvideSupply)
admin.site.register(Room)
admin.site.register(Roomtype)
admin.site.register(RoomRent)
admin.site.register(Services)
admin.site.register(Souvenir)
admin.site.register(SouvenirBrand)
admin.site.register(Spa)
admin.site.register(StorePic)
admin.site.register(Supplier)
admin.site.register(Supply)
admin.site.register(SupplyInRoom)
admin.site.register(SupplyType)
admin.site.register(TimeActivity)
admin.site.register(Zonee)